services:
  mathkids:
    build: .
    container_name: mathkids
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      OCI_USER: ${OCI_USER}
      OCI_PASSWORD: ${OCI_PASSWORD}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./app:/app
    labels:
      - com.centurylinklabs.watchtower.enable=false
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

