create user mathkids identified by "***********";
grant connect, resource to mathkids;

CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50)   NOT NULL,
    password_hash  VARCHAR2(255)  NOT NULL,
    email          VARCHAR2(100)  NOT NULL,
    role           VARCHAR2(20)   DEFAULT 'USER',
    account_status VARCHAR2(20)   DEFAULT 'ACTIVE',
    birth_date     DATE,
    created_at     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP
);


CREATE UNIQUE INDEX idx_users_username ON users(username);
CREATE UNIQUE INDEX idx_users_email ON users(email);
CREATE SEQUENCE mathkids.USER_SEQ START WITH 1;

CREATE TABLE quiz_results (
    result_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER         NOT NULL,
    quiz_level      VARCHAR2(10)   NOT NULL,
    total_questions NUMBER         NOT NULL,
    score           NUMBER         NOT NULL,
    total_time_sec  NUMBER         NOT NULL,
    avg_time_sec    NUMBER(10,2),
    created_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quiz_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


CREATE INDEX idx_quiz_user ON quiz_results(user_id);
CREATE INDEX idx_quiz_level ON quiz_results(quiz_level);
CREATE INDEX idx_quiz_created ON quiz_results(created_at);

insert into mathkids.users(USER_ID, USERNAME, PASSWORD_HASH, ROLE, ACCOUNT_STATUS, EMAIL)
values(0,'guest','dummy','USER','ACTIVE','dummy@gmail.com');

commit;
select * from mathkids.quiz_results;

select a.RESULT_ID, b.username, a.QUIZ_LEVEL, a.TOTAL_QUESTIONS, a.SCORE,
a.TOTAL_TIME_SEC SEC, a.AVG_TIME_SEC AVG_SEC,
a.CREATED_AT + 7/24 CREATED_AT7
from mathkids.quiz_results a
left join mathkids.users b
on a.user_id = b.user_id
order by a.CREATED_AT;

create or replace view mathkids.v_score_daily_by_user as
select
	a.USER_ID,
	sum(a.SCORE) SCORE,
	sum(a.TOTAL_TIME_SEC) SEC,
	sum(a.TOTAL_TIME_SEC)/sum(a.SCORE) AVG_SCORE
from mathkids.quiz_results a
where a.CREATED_AT + 7/24 > TRUNC(SYSDATE) + 7/24
group by a.USER_ID;

create or replace view mathkids.v_score_monthly_by_user as
select
	a.USER_ID,
	sum(a.SCORE) SCORE,
	sum(a.TOTAL_TIME_SEC) SEC, 
	sum(a.TOTAL_TIME_SEC)/sum(a.SCORE) AVG_SCORE
from mathkids.quiz_results a
where a.CREATED_AT + 7/24 > TRUNC(SYSDATE, 'MM') + 7/24
group by a.USER_ID;
